# fly.toml app configuration file generated for homesquad-json-server on 2023-07-06T19:17:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "homesquad-json-server"
primary_region = "eze"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[build]
  dockerfile = "/Dockerfile"
